# Listas vs arrays


In [2]:
lista = [1,2,3,4,5]

## Operaciones con listas

In [3]:
lista + 2

TypeError: can only concatenate list (not "int") to list

In [7]:
lista*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [9]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

### 1. Sumar x cantidad a cada elemento de la lista

In [10]:
lista

[1, 2, 3, 4, 5]

In [14]:
def suma(lista, numero):
#     resultado = []
#     for elemento in lista:
#         resultado.append(elemento+numero)
#     return (resultado)
    return [elemento + numero for elemento in lista]
    

In [16]:
suma(lista,-5)

[-4, -3, -2, -1, 0]

## Operaciones con arrays

In [18]:
import numpy as np

In [19]:
array = np.array([1,2,3,4,5])

In [21]:
array = np.asarray(lista)

In [27]:
array = np.arange(1,6,1)

In [28]:
array

array([1, 2, 3, 4, 5])

In [30]:
array+2

array([3, 4, 5, 6, 7])

In [31]:
array-100

array([-99, -98, -97, -96, -95])

In [32]:
lista*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [33]:
array*2

array([ 2,  4,  6,  8, 10])

In [35]:
array**5

array([   1,   32,  243, 1024, 3125], dtype=int32)

In [36]:
array**(1/2)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

### 2. Crea un función que calcule la potencia de cada velocidad en una lista de velocidades

In [38]:
## Para una lista
def potencia_lista(vels, A=1, rho=1.225):
#     resultado = []
#     for elemento in vels:
#         resultado.append(0.5*rho*A*elemento**3)
#     return resultado
    return [0.5*rho*A*elemento**3 for elemento in vels]

In [40]:
potencia_lista(lista)    

[0.6125, 4.9, 16.5375, 39.2, 76.5625]

In [43]:
def potencia_array(vels, A=1, rho=1.225):
    return 0.5*rho*A*vels**3

In [44]:
potencia_array(lista)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [49]:
%%timeit
potencia_array(array)

3.23 µs ± 134 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
%%timeit
potencia_lista(array)

18.8 µs ± 1.18 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [51]:
%%timeit
potencia_lista(lista)

1.95 µs ± 258 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 3. Crea una función que calcule el producto punto entre dos listas
Input
```python
a = [4,10,-2]
b = [-1,5,3]
```
____
Output
```python
40
```

In [52]:
# 4*-1 + 10*5 + -2*3 = 40

In [64]:
a = [4,10,-2]
b = [-1,5,3,5]

In [65]:
# An array-like is any Python object that np.array can convert to an ndarray

np.dot(a,b)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [53]:
a = [[4,10,2],[-1,5,5]]
a 

[[4, 10, 2], [-1, 5, 5]]

### 4. Escribe un programa que devuelva una lista de los valores diferentes entre dos listas. La lista de salida regresará, en orden ascendente, los valores únicos que están en la lista 1 pero no en la lista 2.
Input
```python

lista1 = [0,10,20,40,60,80]
lista2 = [10,30,40,50,70,90]
```
____
Output

[0,20,60,80]

In [56]:
lista1 = [0,10,20,40,60,80]
lista2 = [10,30,40,50,2000,90]

In [66]:
np.setdiff1d(lista1,lista2)

array([ 0, 20, 60, 80])

### 5. Escribe un programa para hallar el primer índices de los valores máximos y mínimos de una lista unidimensional.
Output
```python
lista = [8,16,2,5,11,10]
```
___
Input:

Indice Minimo: 2, Indice Máximo: 1

In [14]:
lista = [8,16,2,5,11,10]