### NumPy

El módulo NumPy proporciona un objeto ndarray que podemos usar para realizar operaciones en una arreglo de cualquier dimensión. El ndarray significa arreglo de N dimensiones donde N es cualquier número. Eso significa que los arreglos NumPy puede ser de cualquier dimensión.

NumPy tiene una serie de ventajas sobre las listas de Python. Podemos realizar operaciones de alto rendimiento en los arreglos NumPy, tales como:


* Ordenar los miembros de un arreglo
* Operaciones matemáticas y lógicas.
* Funciones de entrada / salida
* Operaciones estadísticas y de álgebra lineal.

#### Instalando numpy

In [ ]:
import sys
!{sys.executable} -m pip install numpy

#### Importando numpy

In [155]:
import numpy as np

Creando un arreglo con numpy

In [156]:
a = np.array([1,2,3])
a

array([1, 2, 3])

En el ejemplo anterior simplemente hemos creado un array unidimensional conteniendo los valores 1, 2, 3. Podemos aplicarle una función que eleva cada valor del array al cuadrado:

In [157]:
np.square(a)

array([1, 4, 9])

In [158]:
a

array([1, 2, 3])

O, si tenemos otro array o un escalar, podemos realizar operaciones entre ellos:


In [159]:
b= np.array([5,6,7])

In [160]:
a + b

array([ 6,  8, 10])

In [161]:
a - 2

array([-1,  0,  1])

Los arrays son contenedores multidimensionales para datos homogéneos. Es decir, todos los datos contenidos en un array deberán ser del mismo tipo. Todos los arrays tiene un número de dimensiones (ndim), un tamaño (shape) que define el número de elementos en cada dimensión del array, y un tipo (dtype) que describe el tipo de los datos contenidos en el array.

La función numpy.array es la forma más simple de crear un array a partir de un iterador como una simple lista (el iterador también puede ser otro array NumPy). En este ejemplo, partimos de una lista n y creamos un array, mostrando el número de dimensiones (atributo ndim), su tamaño (accesible a través de su atributo shape) y el tipo de los datos que contiene (accesible a través de su atributo dtype):

In [162]:
n=[1,2,3]
m=np.array(n)
m

array([1, 2, 3])

In [163]:
m.dtype

dtype('int64')

In [164]:
m.ndim

1

In [165]:
m.shape

(3,)

El atributo shape devuelve una tupla con tantas cifras como dimensiones tiene el array, y cada cifra indica el número de elementos en la correspondiente dimensión (este atributo también puede ser usado para fijar el tamaño del array).

En este caso vemos que el array m recién creado tiene una única dimensión y 3 elementos en dicha dimensión. El tipo de los valores contenidos en él es int32 (enteros representados con 32 bits).

Si alguno de los datos de la lista n utilizada hubiese sido un número real, por ejemplo, la función array habría modificado el tipo del array creado para adoptar uno que englobase a todos los tipos involucrados en la lista -en este caso el tipo float correspondiente a los números reales-:

In [167]:
n=[1.0,2,3]
m=np.array(n)
print(m.shape)
print(m.dtype)
print(m)

(3,)
float64
[1. 2. 3.]


En un caso extremo, la función adoptaría como tipo común la cadena de texto (string):


In [168]:
n=[1.0,'a',3]
m=np.array(n)
print(m.dtype)
print(m)

<U32
['1.0' 'a' '3']


En este ejemplo, la lista a partir de la que se crea el array incluye números enteros, números reales y un string, siendo este último tipo el único capaz de englobar a todos ellos, por lo que el tipo del array pasa a ser "<U32", cadena de texto con caracteres unicode codificado como "little-endian" (con el bit menos significativo situado a la izquierda, lo que sabemos por el símbolo "<"). En la imagen se muestra también el array creado, quedando claro el tipo de sus elementos. Este proceso de modificación del tipo de forma que englobe a todos los tipos del iterador a partir del cual se crea el array es lo que se conoce como coerción de tipo.

Esta función permite fijar el tipo del array con el parámetro dtype:

In [171]:
a= np.array([1,2,3], dtype="float32")
a.dtype

dtype('float32')

Si especificamos un tipo genérico como float (sin especificar el número de bytes), se asignará el tamaño por defecto para dicho tipo (64, como vemos en la imagen anterior). Si quisiéramos especificar el número de bits, podríamos hacerlo también:

In [ ]:
a.dtype

#### Arrays de dos dimensiones

Si los elementos son estructuras más complejas -otras listas, por ejemplo- cada elemento principal de la lista se considera una fila en un array de dos dimensiones, y los elementos contenidos en dichos elementos se consideran repartidos en columnas:

In [172]:
m = np.array([[10,11,12],
            [12,14,15]])
print(m.shape)
print(m)

(2, 3)
[[10 11 12]
 [12 14 15]]


En el ejemplo anterior, la lista principal consta de dos elementos: el primero ([10, 11, 12]) constituye la primera fila del array, y el segundo ([13, 14, 15]) la segunda fila. Como ambos elementos son, a su vez, listas, cada uno de los elementos de estas listas se muestran en columnas.

El eje vertical recibe el nombre de "eje 0", y el eje horizontal "eje 1".

Obsérvese que un array unidimensional como el visto al principio de esta sección no es lo mismo que un array bidimensional de una fila y tres columnas:

In [173]:
m=np.array([[1,2,3]])
print(m.shape)
print(m)

(1, 3)
[[1 2 3]]


El tamaño de este array es (1, 3) -una fila y tres columnas-. La diferencia está en la lista usada para crear el array: en el ejemplo del array unidimensional se trataba de una simple lista de números ([1, 2, 3]) mientras que en el array recién creado se trata de una lista cuyo único elemento es otra lista de tres elementos (de ahí los dobles corchetes).

#### Arrays de tres dimensiones
Si, a su vez, los elementos de segundo nivel son listas de elementos, nos encontramos ante un array de tres dimensiones:

In [174]:
m= np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[11,12,13],[14,15,16],[17,18,19]]])

print(m.shape)
print(m)

(2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


El esquema mostrado por la instrucción print(m) muestra que el primer elemento de la lista usada para crear el array ([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) sigue siendo considerado como la primera fila del nuevo array, y el segundo elemento ([11, 12, 13], [14, 15, 16], [17, 18, 19]]) como la segunda fila. Es decir, la primera dimensión ocupa el eje vertical (eje 0).

Si nos imaginamos que esta estructura es una especie de cubo de Rubik, entendemos que los elementos del segundo nivel siguen mostrándose en columnas (eje horizontal, llamado eje 1) y que los del tercer nivel se muestran en el eje perpendicular a los anteriores (eje 2), llegamos a la conclusión de que el esquema mostrado por NumPy al imprimir el array nos sitúa en la vertical de la estructura, mirándola desde arriba (viendo los dos "pisos" simultáneamente: el piso superior encima y el inferior, debajo):

<img src="https://interactivechaos.com/sites/default/files/inline-images/tutorial_numpy_ejemplos_arrays_05.JPG">

#### La función arange

Otra función que nos permite crear un array NumPy es numpy.arange. Al igual que la función predefinida de Python range, genera un conjunto de números entre un valor de inicio y uno final, pudiendo especificar un incremento entre los valores, pero, al contrario de lo que ocurre con range, el resultado aquí es un array NumPy:


In [175]:
a= np.arange(2,10,3)
a

array([2, 5, 8])

Si no especificamos el tercer argumento, se sobreentiende que el incremento es de 1:


In [176]:
a= np.arange(2,8)
a

array([2, 3, 4, 5, 6, 7])

Si solo añadimos un valor como argumento, la función considera todos los valores desde el cero hasta dicho valor (sin incluirlo, como ya sabemos):

In [177]:
np.arange(5)

array([0, 1, 2, 3, 4])

De los dos argumentos que definen los límites inferior y superior, el primer valor puede ser mayor que el segundo si se indica un incremento negativo:

In [178]:
a = np.arange(10,2,-3)
a

array([10,  7,  4])

linspace

La función numpy.linspace genera un array NumPy formado por n números equiespaciados entre dos dados. Su sintaxis es:

numpy.linspace(valor-inicial, valor-final, número de valores)

In [179]:
a= np.linspace(10,40,4, dtype="int")
a

array([10, 20, 30, 40])

Obsérvese que, por defecto, el array generado incluye el valor final (este comportamiento es configurable).

Como en la práctica totalidad de funciones de creación de arrays NumPy, podemos especificar el tipo del array usando el parámetro dtype:

In [183]:
a = np.linspace(10, 42, 100 , dtype = "float")
a

array([10.        , 10.32323232, 10.64646465, 10.96969697, 11.29292929,
       11.61616162, 11.93939394, 12.26262626, 12.58585859, 12.90909091,
       13.23232323, 13.55555556, 13.87878788, 14.2020202 , 14.52525253,
       14.84848485, 15.17171717, 15.49494949, 15.81818182, 16.14141414,
       16.46464646, 16.78787879, 17.11111111, 17.43434343, 17.75757576,
       18.08080808, 18.4040404 , 18.72727273, 19.05050505, 19.37373737,
       19.6969697 , 20.02020202, 20.34343434, 20.66666667, 20.98989899,
       21.31313131, 21.63636364, 21.95959596, 22.28282828, 22.60606061,
       22.92929293, 23.25252525, 23.57575758, 23.8989899 , 24.22222222,
       24.54545455, 24.86868687, 25.19191919, 25.51515152, 25.83838384,
       26.16161616, 26.48484848, 26.80808081, 27.13131313, 27.45454545,
       27.77777778, 28.1010101 , 28.42424242, 28.74747475, 29.07070707,
       29.39393939, 29.71717172, 30.04040404, 30.36363636, 30.68686869,
       31.01010101, 31.33333333, 31.65656566, 31.97979798, 32.30

In [184]:
print(a.dtype)
print(a.shape)

float64
(100,)


logspace

De forma semejante, la función numpy.logspace genera un array NumPy formado también por n números entre dos dados, pero en una escala logarítmica. Por ejemplo:

In [185]:
m = np.logspace(2, 3, 10)
m

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

La base a aplicar (por defecto 10) puede especificarse en el argumento base.

El resultado de esta función es equivalente a calcular los valores usando la función linspace vista y, a continuación, calcular la base elevada a cada uno de los números obtenidos:

In [186]:
m = np.linspace(2, 3, 10)
m

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [187]:
np.power(10, m)

array([ 100.        ,  129.1549665 ,  166.81005372,  215.443469  ,
        278.25594022,  359.38136638,  464.15888336,  599.48425032,
        774.26368268, 1000.        ])

Es posible crear arrays mediante otras funciones:

numpy.zeros(): devuelve un array del tamaño y tipo indicados inicializando sus valores con ceros
numpy.ones(): devuelve un array del tamaño y tipo indicados inicializando sus valores con unos
numpy.empty(): devuelve un array del tamaño y tipo indicados sin inicializar sus valores
En los tres casos se puede especificar el tamaño deseado con el parámetro shape, que deberá contener un número entero (si se desea crear un array unidimensional) o una tupla de enteros (si se desea crear un array multidimensional):

In [188]:
m=np.ones(shape = (2,3))
print(m)

[[1. 1. 1.]
 [1. 1. 1.]]


#### El método astype

Es posible hacer un copia de un array aplicándole otro tipo de datos utilizando el método asociado a un array numpy.ndarray.astype():

In [191]:
n=np.asarray([1.1,2.2,3.3])
print(m.dtype)


float64


In [192]:
m=n.astype("int32")
print(m.dtype)
print(m)

int32
[1 2 3]


También podemos crear un array de números a partir de un array que contenga textos representando números:

In [193]:
n= np.asarray(["1","2","3"])
print(n.dtype)

<U1


In [194]:
m=n.astype("int32")
print(m.dtype)
print(m)

int32
[1 2 3]


#### Indexado y selección

Hay diferentes métodos para indexar y realizar selecciones en un array NumPy en función del número de dimensiones que tenga...

Si se trata de un array unidimensional, la selección se realiza de modo semejante a las listas.

Los índices comienzan en cero. Si el índice es negativo, estamos contando desde el final (y el último valor tiene índice -1):

In [195]:
m = np.array([1,2,3,4,5])

In [196]:
print(m[0])

1


In [197]:
print(m[2])

3


In [ ]:
Rangos

In [198]:
print(m[1:3])

[2 3]


In [199]:
print(m[:3])

[1 2 3]


In [200]:
print(m[3:])

[4 5]


Tercer argumento en los rangos



In [201]:
m=np.arange(20)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [202]:
m[1:12:2]

array([ 1,  3,  5,  7,  9, 11])

El incremento también puede ser negativo, siempre que el primer valor apunte a un valor posterior al segundo:

In [203]:
m[12:1:-2]

array([12, 10,  8,  6,  4,  2])

#### Selecciones en arrays multidimensionales

Si se trata, por ejemplo, de arrays bidimensionales, los elementos correspondientes a cada índice ya no son escalares, sino arrays unidimensionales (filas).

Partamos, por ejemplo, de este array de ejemplo (generado con la función integrada de Python range y redimensionado con la función numpy.reshape):

In [205]:
a.shape

(5, 5)

In [206]:
a[1]

array([ 6,  7,  8,  9, 10])

In [207]:
a[-2]

array([16, 17, 18, 19, 20])

In [208]:
a[1][2]

8

In [204]:
a= np.reshape(np.array(range(1,26)),(5,5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [209]:
#más simple
a[1,2]

8

Estos índices pueden ser rangos del tipo a:b. En el siguiente ejemplo estamos extrayendo los elementos que pertenecen a las filas 1 y 2 y columna 3 (recordemos que los índices comienzan en cero):

In [211]:
a[1:3,3]

array([ 9, 14])

En este otro ejemplo estamos seleccionando los elementos que pertenecen a las filas 1 y 2, y columnas 2 y 3:

In [212]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

#### Selección con booleanos

Partamos del siguiente array de una dimensión y 7 elementos:



In [213]:
a= np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [216]:
mask=[True,True,False,True,False,False,True]
print(a[mask])

[1 2 4 7]


In [218]:
mask=a>3
print(mask)
print(a[mask])

[False False False  True  True  True  True]
[4 5 6 7]


In [222]:
### Ordenar
a= np.array([-2,1,0,4,-3])
print(np.sort(a))
print(a)

[-3 -2  0  1  4]
[-2  1  0  4 -3]


In [223]:
a= np.array([-2,1,0,4,-3])
a.sort()
print(a)

[-3 -2  0  1  4]


In [225]:
#Operaciones entre arrays
a= np.array([[1,2,3],
           [4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [226]:
a+1

array([[2, 3, 4],
       [5, 6, 7]])

In [227]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

Usando dos arrays

In [228]:
a= np.array([[1,2,3],
           [4,5,6]])
b= np.array([[2,4,2],
           [0,-2,-4]])

In [229]:
print(a+b)

[[3 6 5]
 [4 3 2]]


In [232]:
### apuntando al mismo arreglo
a= np.array([1,2,3])
b=a[:]
print(b)
b[0]=100
print(b)
print(a)

[1 2 3]
[100   2   3]
[100   2   3]


In [234]:
###Copiando arreglos
a=np.array([1,2,3])
b=a[:].copy() #forzando la copia
#print(b)
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


Referencia

https://interactivechaos.com/es/manual/tutorial-de-numpy/